import './slider/_home-hero-slider.js'
import './slider/_realized-projects-slider.js'
import './slider/_documents-slider.js'
import './slider/_reviews-slider.js'
import './slider/_brands-slider.js'
import './slider/_image-slider.js'
import './slider/_planning-slider.js'
import './slider/_other-news-slider.js'